CREATE DATABASE IF NOT EXISTS bt10;
USE bt10;

CREATE TABLE TAC_GIA (
    MaTacGia INT AUTO_INCREMENT PRIMARY KEY,
    TenTacGia NVARCHAR(150) NOT NULL,
    MoTa NVARCHAR(500)
);

CREATE TABLE TAI_KHOAN (
    MaTaiKhoan INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    MatKhauHash VARCHAR(255) NOT NULL,
    VaiTro VARCHAR(30) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL,
    NgayTao DATETIME NOT NULL
);

CREATE TABLE KHACH_HANG (
    MaKH INT AUTO_INCREMENT PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(20) NOT NULL,
    Email VARCHAR(100),
    DiaChi NVARCHAR(255),
    MaTaiKhoan INT,
    NgayDangKy DATETIME NOT NULL,
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN(MaTaiKhoan)
);

CREATE TABLE NHAN_VIEN (
    MaNV INT AUTO_INCREMENT PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(20) NOT NULL,
    Email VARCHAR(100),
    DiaChi NVARCHAR(255),
    ChucVu VARCHAR(30) NOT NULL,
    MaTaiKhoan INT,
    NgayVaoLam DATE,
    TrangThai VARCHAR(20) NOT NULL,
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN(MaTaiKhoan)
);

CREATE TABLE KHUYEN_MAI (
    MaKM INT AUTO_INCREMENT PRIMARY KEY,
    TenKM NVARCHAR(150) NOT NULL,
    MaCode VARCHAR(50),
    LoaiGiam VARCHAR(20) NOT NULL,
    GiaTriGiam DECIMAL(18,2) NOT NULL,
    GiamToiDa DECIMAL(18,2),
    DonToiThieu DECIMAL(18,2),
    SoLuongToiDa INT,
    SoLuongDaDung INT NOT NULL,
    NgayBatDau DATETIME NOT NULL,
    NgayKetThuc DATETIME NOT NULL,
    TrangThai VARCHAR(20) NOT NULL
);

CREATE TABLE DANH_MUC (
    MaDanhMuc INT AUTO_INCREMENT PRIMARY KEY,
    TenDanhMuc NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(500),
    TrangThai BIT NOT NULL
);

CREATE TABLE NHA_CUNG_CAP (
    MaNCC INT AUTO_INCREMENT PRIMARY KEY,
    TenNCC NVARCHAR(150) NOT NULL,
    DiaChi NVARCHAR(255),
    SoDienThoai VARCHAR(20),
    Email VARCHAR(100),
    MaSoThue VARCHAR(50),
    TrangThai VARCHAR(20) NOT NULL
);

CREATE TABLE NHA_XUAT_BAN (
    MaNXB INT AUTO_INCREMENT PRIMARY KEY,
    TenNXB NVARCHAR(150) NOT NULL,
    DiaChi NVARCHAR(255),
    SoDienThoai VARCHAR(20),
    Email VARCHAR(100)
);

CREATE TABLE SAN_PHAM (
    MaSP INT AUTO_INCREMENT PRIMARY KEY,
    TenSP NVARCHAR(200) NOT NULL,
    MaDanhMuc INT NOT NULL,
    MaNXB INT,
    MaNCC INT,
    LoaiSP VARCHAR(30) NOT NULL,
    ISBN VARCHAR(20),
    GiaBan DECIMAL(18,2) NOT NULL,
    SoLuongTon INT NOT NULL,
    MucTonToiThieu INT NOT NULL,
    MoTa NVARCHAR(1000),
    TrangThai VARCHAR(20) NOT NULL,
    NgayTao DATETIME NOT NULL,
    FOREIGN KEY (MaDanhMuc) REFERENCES DANH_MUC(MaDanhMuc),
    FOREIGN KEY (MaNXB) REFERENCES NHA_XUAT_BAN(MaNXB),
    FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC)
);

CREATE TABLE SAN_PHAM_TAC_GIA (
    MaSP INT NOT NULL,
    MaTacGia INT NOT NULL,
    ThuTuTacGia INT,
    PRIMARY KEY (MaSP, MaTacGia),
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP),
    FOREIGN KEY (MaTacGia) REFERENCES TAC_GIA(MaTacGia)
);

CREATE TABLE KHUYEN_MAI_SAN_PHAM (
    MaKM INT NOT NULL,
    MaSP INT NOT NULL,
    PRIMARY KEY (MaKM, MaSP),
    FOREIGN KEY (MaKM) REFERENCES KHUYEN_MAI(MaKM),
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE GIO_HANG (
    MaGioHang INT AUTO_INCREMENT PRIMARY KEY,
    MaKH INT NOT NULL,
    NgayTao DATETIME NOT NULL,
    NgayCapNhat DATETIME NOT NULL,
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
);

CREATE TABLE CHI_TIET_GIO_HANG (
    MaGioHang INT NOT NULL,
    MaSP INT NOT NULL,
    SoLuong INT NOT NULL,
    PRIMARY KEY (MaGioHang, MaSP),
    FOREIGN KEY (MaGioHang) REFERENCES GIO_HANG(MaGioHang),
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE DON_HANG (
    MaDH INT AUTO_INCREMENT PRIMARY KEY,
    NgayDat DATETIME NOT NULL,
    MaKH INT NOT NULL,
    SoDienThoaiGiao VARCHAR(20) NOT NULL,
    DiaChiGiao NVARCHAR(255) NOT NULL,
    TongTien DECIMAL(18,2) NOT NULL,
    TrangThai VARCHAR(30) NOT NULL,
    LyDoTuChoi NVARCHAR(500),
    LyDoHuy NVARCHAR(500),
    NgayXacNhan DATETIME,
    NgayHoanThanh DATETIME,
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
);

CREATE TABLE CHI_TIET_DON_HANG (
    MaDH INT NOT NULL,
    MaSP INT NOT NULL,
    SoLuong INT NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,
    ThanhTien DECIMAL(18,2) NOT NULL,
    PRIMARY KEY (MaDH, MaSP),
    FOREIGN KEY (MaDH) REFERENCES DON_HANG(MaDH),
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE HOA_DON (
    MaHD INT AUTO_INCREMENT PRIMARY KEY,
    MaDH INT NOT NULL,
    MaNV INT NOT NULL,
    NgayLap DATETIME NOT NULL,
    MaKM INT,
    TienGiam DECIMAL(18,2) NOT NULL,
    TongTienThanhToan DECIMAL(18,2) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL,
    FOREIGN KEY (MaDH) REFERENCES DON_HANG(MaDH),
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE THANH_TOAN (
    MaThanhToan INT AUTO_INCREMENT PRIMARY KEY,
    MaDH INT NOT NULL,
    PhuongThuc VARCHAR(30) NOT NULL,
    TrangThai VARCHAR(30) NOT NULL,
    SoTien DECIMAL(18,2) NOT NULL,
    NgayThanhToan DATETIME,
    MaGiaoDich VARCHAR(100),
    NoiDung NVARCHAR(500),
    FOREIGN KEY (MaDH) REFERENCES DON_HANG(MaDH)
);

CREATE TABLE PHIEU_NHAP (
    MaPN INT AUTO_INCREMENT PRIMARY KEY,
    MaNCC INT NOT NULL,
    MaNV INT NOT NULL,
    NgayNhap DATETIME NOT NULL,
    TongTien DECIMAL(18,2) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL,
    GhiChu NVARCHAR(500),
    FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC),
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE CHI_TIET_PHIEU_NHAP (
    MaPN INT NOT NULL,
    MaSP INT NOT NULL,
    SoLuong INT NOT NULL,
    DonGiaNhap DECIMAL(18,2) NOT NULL,
    ThanhTien DECIMAL(18,2) NOT NULL,
    PRIMARY KEY (MaPN, MaSP),
    FOREIGN KEY (MaPN) REFERENCES PHIEU_NHAP(MaPN),
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE PHIEU_KIEM_KE (
    MaPhieuKiemKe INT AUTO_INCREMENT PRIMARY KEY,
    NgayKiemKe DATETIME NOT NULL,
    MaNV INT NOT NULL,
    TrangThai VARCHAR(30) NOT NULL,
    MaNVPheDuyet INT,
    NgayPheDuyet DATETIME,
    GhiChu NVARCHAR(500),
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV),
    FOREIGN KEY (MaNVPheDuyet) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE CHI_TIET_KIEM_KE (
    MaPhieuKiemKe INT NOT NULL,
    MaSP INT NOT NULL,
    SoLuongHeThong INT NOT NULL,
    SoLuongThucTe INT NOT NULL,
    ChenhLech INT NOT NULL,
    LyDo NVARCHAR(500),
    PRIMARY KEY (MaPhieuKiemKe, MaSP),
    FOREIGN KEY (MaPhieuKiemKe) REFERENCES PHIEU_KIEM_KE(MaPhieuKiemKe),
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE PHIEU_TRA_HANG (
    MaPhieuTra INT AUTO_INCREMENT PRIMARY KEY,
    MaNCC INT NOT NULL,
    MaNV INT NOT NULL,
    NgayTra DATETIME NOT NULL,
    LyDo NVARCHAR(500) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL,
    GhiChu NVARCHAR(500),
    FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC),
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE CHI_TIET_TRA_HANG (
    MaPhieuTra INT NOT NULL,
    MaSP INT NOT NULL,
    SoLuong INT NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,
    ThanhTien DECIMAL(18,2) NOT NULL,
    PRIMARY KEY (MaPhieuTra, MaSP),
    FOREIGN KEY (MaPhieuTra) REFERENCES PHIEU_TRA_HANG(MaPhieuTra),
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE DANH_GIA (
    MaDanhGia INT AUTO_INCREMENT PRIMARY KEY,
    MaKH INT NOT NULL,
    MaSP INT NOT NULL,
    MaDH INT NOT NULL,
    SoSao INT NOT NULL,
    NoiDung NVARCHAR(1000),
    NgayDanhGia DATETIME NOT NULL,
    TrangThai VARCHAR(20) NOT NULL,
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH),
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP),
    FOREIGN KEY (MaDH) REFERENCES DON_HANG(MaDH)
);

-- Users table fallback (Spring maps to 'users' currently)
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name NVARCHAR(100) NOT NULL
);
